<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <DefineConstants>STATIC_MAP_TESTS</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../src/SeaOfStarsLocalMap/StaticFog.cs" Link="StaticFog.cs" />
    <Compile Include="../../src/SeaOfStarsLocalMap/StaticMapPlugin.cs" Link="StaticMapPlugin.cs" />
  </ItemGroup>
</Project>
